<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="camera_sensor_macro.xacro"/>
  <!-- Camera joint: poziționează camera pe robot -->
    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <!-- Calcul pentru camera ca sa stea lipita de sasiu -->
        <origin xyz="${chassis_length} 0 ${chassis_height + 0.025}" rpy="0 -0.2 0"/>
    </joint>
    <!-- Link minim pentru camera -->
    <link name="camera_link">
        <visual>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="blue">
            <color rgba="0 0 1 1"/>
        </material>
        </visual>

        <collision>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        </collision>

        <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0"
                izz="0.0001"/>
        </inertial>
    </link>

    <gazebo reference="camera_link">
        <xacro:camera_sensor_macro/>
    </gazebo>

</robot>
